### ISSUE TITLE
[Locale Incompatibility] Postgresql 9.2.4 closing connection on error

### ISSUE THREAD

**Issue by ivanromanko** [python-postgres/fe#67] opened 2013-06-07 12:11 UTC
Hello!
Here is the code, connecting to Postgresql 9.2.4 on Ubuntu 12.04 with python3.2/python3.3:
import postgresql
dbh = postgresql.open('pq://user:pass@db/database')
dbh.prepare('select 1')()
    [(1,)]
dbh.prepare('select \* from fsdsfsdfskdh')() # not existing table
    postgresql.exceptions.UndefinedTableError: relation "fsdsfsdfskdh" does not exist
dbh.prepare('select 1')()
    postgresql.exceptions.UndefinedTableError: relation "fsdsfsdfskdh" does not exist # the same error again
dbh.state
    'closed'

But these lines works well with Postgresql 8.4.4 with python3.2/python3.3.
Is this a bug or feature?

**Comment by jwp** [comment] 2020-12-06 22:49
Is this still an issue?

**Comment by jwp** [comment] 2020-12-08 17:21
Duplicate of #63

**Closed by jwp** 2020-12-08 17:21 UTC
